### PR TITLE
fix: update package locks

### LINKED ISSUE #494: `npm i` fails on fresh clone
Error as follows.

```bash
> loopback4-example-shopping-monorepo@1.1.1 postinstall /i/dev/loopback4-example-shopping
> lerna bootstrap

lerna notice cli v3.20.2
lerna info Bootstrapping 2 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in 'loopback4-example-shopping'
lerna ERR! npm install stderr:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/loopback4-example-recommender - Not found
npm ERR! 404 
npm ERR! 404  'loopback4-example-recommender@1.1.1' is not in the npm registry.
```

See also: #459

### PR DESCRIPTION
**Pull request by dougal83**
update package locks to resolve issue with initial install

fix #494

### CODE REVIEW

**Comment by vernandoRGN** [comment]
Same issue, hopes this will fix it

**Comment by dougal83** [comment]
> Same issue, hopes this will fix it

If you wish to proceed without waiting, delete all three package lock files listed under files changed on this PR.  Then all you need to do is `npm i`, it will just take longer to start...

**Comment by Vernando05** [comment]
> > Same issue, hopes this will fix it
> 
> If you wish to proceed without waiting, delete all three package lock files listed under files changed on this PR. Then all you need to do is `npm i`, it will just take longer to start...

already cherry-picked your commit, thanks!

**Comment by dougal83** [comment]
Resolved by #500

**Pull request closed without merging**
