### PR TITLE
refactor: change duplicate email error

### PR DESCRIPTION
**Pull request by dougal83**
Change user controller email conflict error to 'UnprocessableEntity' as more appropriate.

Signed-off-by: Douglas McConnachie <dougal83+git@gmail.com>

### CODE REVIEW

**Comment by nabdelgadir** [comment]
@dougal83 Can you explain why `UnprocessibleEntity` is more appropriate (just for my knowledge)? Looking at the description for [`Conflict`](https://httpstatuses.com/409) it says: 

> The request could not be completed due to a conflict with the current state of the target resource. This code is used in situations where the user might be able to resolve the conflict and resubmit the request.

Either way, CI is failing because of changing `HttpError` to `ResponseError`, because `ResponseError` doesn't have a `text` property.

**Comment by dougal83** [comment]
Hey @nabdelgadir 
I thought it might be worth revisiting the code. I originally chose Conflict but its come up in conversation on three separate occasions since that some people believe UnprocessibleEntity is more appropriate.  Basically; UnprocessibleEntity is concerned with the current object(new user) having an issue and Conflict argued that must be an _existing_ object being acted on with conflict.

I'm personally happy, to leave it as is.  If you agree it's fine then I'm in! ;)

**Comment by dougal83** [comment]
Happy to leave as is.

**Comment by nabdelgadir** [comment]
Hi @dougal83, thanks for the explanation! I'm good with changing it or keeping it as it, but I think it's worth seeing what @hacksparrow and @jannyHou think about it in this case.

**Pull request closed without merging**
