### PR TITLE
[DO NOT MERGE] feat: add API code generator for JavaScript

### PR DESCRIPTION
**Pull request by dougal83**
Hey @hacksparrow 
An implementation if you wish to take a look at starting point.  Some work to do but it's a base for #479 if it helps.

Add API code generator for JavaScript.  Includes generated code.

### CODE REVIEW

**Comment by hacksparrow** [comment]
@dougal83 thanks for the effort, but this PR is a little early. Let's land https://github.com/strongloop/loopback4-example-shopping/pull/468 first. We are planning to even break that PR into smaller ones.

**Comment by hacksparrow** [comment]
@dougal83 #468 has landed. Do you want to rebase and update this PR?

**Comment by dougal83** [comment]
No problem, all done (hopefully correctly!).  Please let me know if the Js generator produces decent code.  I've been using the angular typescript generator and it's great.
Diana mentioned [an alternate implementation](https://github.com/strongloop/loopback4-example-shopping/issues/479#issuecomment-574863071) too.  I'd be interested if you improve the implementation too.

There are little things to improve incrementally like `InlineResponse`s.  With the angular-typescript generator you can give the schema a title and it will use that.  Hopefully Js generator is similar.

**Comment by dougal83** [comment]
I thought I was going crazy...  didn't spot the target branch was deleted.  Thought it was me.

merge 2 commits into **strongloop:website** from dougal83:website-codegen

**Comment by hacksparrow** [comment]
@dougal83 will take a look at it in detail when it is time to implement the API code generator, thanks.

**Comment by dougal83** [comment]
Closing example, not needed to be open PR.

**Pull request closed without merging**
